/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import estructural.Estudiante;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.IServicioUniversidad;
    
/**
 *
 * @author Cristian Devia
 */
public class GUIModificar extends javax.swing.JFrame {

    private final IServicioUniversidad servicio;
    /**
     * Creates new form GUIModificar
     */
    public GUIModificar(IServicioUniversidad pServicio) {
        servicio = pServicio;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        labNormal = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        labCedula = new javax.swing.JLabel();
        labCorreo = new javax.swing.JLabel();
        labCelular = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labCodigo.setText("Código");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        labNormal.setText("Nombre");

        labCedula.setText("Cédula");

        labCorreo.setText("Correo");

        labCelular.setText("Celular");

        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel1.setText("Edad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(labNormal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labCodigo)
                                        .addGap(8, 8, 8)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(txtNombre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtEdad))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labCedula)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labCorreo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtCorreo))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labCelular)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btnModificar)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNormal)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labCedula)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labCorreo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labCelular)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnModificar)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigo.getText();
        try 
        {
         Estudiante buscado = servicio.buscarEstudiantePorCodigo(codigo);
         if(buscado==null)
         {
             JOptionPane.showMessageDialog(this, "El estudiante no existe");
         }
         else
         {
              
              txtNombre.setText(buscado.getNombre());
              txtCedula.setText(String.valueOf(buscado.getCedula()));
              txtCorreo.setText(buscado.getCorreo());
              txtCelular.setText(String.valueOf(buscado.getCelular()));
              txtEdad.setText(String.valueOf(buscado.getEdad()));
              
         }        
            
        } 
        catch (RemoteException ex) {
            Logger.getLogger(GUIBuscar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
      
        String codigo = txtCodigo.getText();
        
        try 
        {
            Estudiante existe = servicio.buscarEstudiantePorCodigo(codigo);
            if(existe == null)
            {
                JOptionPane.showMessageDialog(this, "El estudiante no existe");
            }
            else if( txtCedula.getText().equals(null) || txtCedula.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Cedula no valida");
            }
            else if( txtCelular.getText().equals(null) || txtCelular.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Celular no valido");
            }
            else if( txtEdad.getText().equals(null) || txtEdad.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Edad no valida");
            }
            else if(txtNombre.getText().equals(null) || txtNombre.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Nombre invalido");
            }
            else if(txtCorreo.getText().equals(null) || txtCorreo.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "correo invalido");
            }            
            
            else
            {
            ArrayList estudiantes = servicio.getEstudiantes();
            boolean centinela = false;
            for(int i= 0;i<estudiantes.size() && centinela ==false;i++)
            {
                String nombre = txtNombre.getText();
                int cedula = Integer.parseInt(txtCedula.getText());
                String correo = txtCorreo.getText();
                int celular = Integer.parseInt(txtCelular.getText());
                int edad = Integer.parseInt(txtEdad.getText());
                Estudiante actual = (Estudiante) estudiantes.get(i);
                
                if(actual.getCedula() == cedula)
                {
                    centinela = true;
                     JOptionPane.showMessageDialog(this, "Existe la cedula");
                }
                else if(actual.getCorreo().equals(actual.getCorreo()))
                {
                    centinela = true;
                     JOptionPane.showMessageDialog(this, "Existe el correo");
                }
                   else if(actual.getCelular() == celular)
                {
                    centinela = true;
                     JOptionPane.showMessageDialog(this, "Existe el celular");
                }
                else
                   {
                        servicio.actualizarPorCodigo(codigo, nombre, cedula, correo, celular, edad);
                         JOptionPane.showMessageDialog(this, "estudiante modificado");
                   }
            }
           
            txtNombre.setText("");
            txtCedula.setText("");
            txtCorreo.setText("");
            txtEdad.setText("");
            txtCelular.setText("");
            txtCodigo.setText("");
            }
            
        } catch (RemoteException ex) {
            Logger.getLogger(GUIModificar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labCedula;
    private javax.swing.JLabel labCelular;
    private javax.swing.JLabel labCodigo;
    private javax.swing.JLabel labCorreo;
    private javax.swing.JLabel labNormal;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
